marks=[]
student1=int(input("enter marks"))
marks.append(student1)
student2=int (input ("enter marks"))
marks.append(student2)
student3=int( input ("enter marks"))
marks.append(student3)
student4=int (input("enter marks"))
marks.append(student4)
student5=int (input ("enter marks"))
marks.append(student5)
student6=int (input ("enter marks"))
marks.append(student6)
marks.sort()

print(marks)